server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:

      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:4200"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true

      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:

        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**

        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
          filters:
            - AuthenticationFilter

        - id: post-service
          uri: lb://post-service
          predicates:
            - Path=/api/posts/**
          filters:
            - AuthenticationFilter

        - id: network-service
          uri: lb://network-service
          predicates:
            - Path=/api/network/**
          filters:
            - AuthenticationFilter

        - id: interaction-service
          uri: lb://interaction-service
          predicates:
            - Path=/api/interactions/**
          filters:
            - AuthenticationFilter

        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/api/notifications/**
          filters:
            - AuthenticationFilter

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/

jwt:
  secret: revconnect-microservices-secret-key-for-jwt-token-generation-minimum-256-bits

management:
  endpoints:
    web:
      exposure:
        include: health,info